### ISSUE TITLE
[Question] Is there a way to prevent jautolock from triggering when watching a movie ?

### ISSUE THREAD

**Issue by HerosDuGouter** [johnchen902/python-jautolock#1]
Something that could reset the timer when sound is playing through pulseaudio, or prevent it from triggering when the mouse is in a certain corner of the screen ?

Thanks :)

**Comment by johnchen902** [comment]
> reset the timer when sound is playing through pulseaudio

To test if audio is playing, consider `pacmd list-sink-inputs | grep -q 'state: RUNNING'`.
Currently there are no integrated way to reset the timer, but you can move the cursor programically (like `xdotool mousemove_relative -- 1 0; xdotool mousemove_relative -- -1 0`).

>  prevent it from triggering when the mouse is in a certain corner of the screen

This script should work:

```
#!/bin/sh
IN_CORNER=0
while true; do
    eval $(xdotool getmouselocation --shell)
    if [[ $IN_CORNER -eq 0 && $X -eq 0 && $Y -eq 0 ]] ; then
        jautolock busy
        IN_CORNER=1
    elif [[ $IN_CORNER -eq 1 && ($X -ne 0 || $Y -ne 0) ]] ; then
        jautolock unbusy
        IN_CORNER=0
    fi
    sleep 1
done
```

**Comment by HerosDuGouter** [comment]
That's perfect ! Thank you, I will try these :)
